<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Invoicer by Suren Dias | Free invoicing for free lancers.</title>
    <link rel="stylesheet" href="css/foundation.css"/>
    <link rel="stylesheet" href="css/foundation-datepicker.css"/>
    <link rel="stylesheet" href="css/style.css"/>
    <script src="js/vendor/modernizr.js"></script>

    <script src='https://www.google.com/recaptcha/api.js'></script>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-35882199-9', 'auto');
        ga('send', 'pageview');

    </script>
</head>
<body>

<div class="row header">
    <div class="large-12 columns">
        <h1>Invoicer &trade; by Suren Dias</h1>
        <p>Free invoicing for freelancers.  <a href="pdf/invoice-001-sample.pdf" target="_blank">Sample Invoice as generated by this tool.</a></p>
        <p class="alert-box info radius">Please note that none of your information is stored or tracked by this tool.</p>
    </div>
</div><!--end header-->

<form action="process_invoice.php" method="post" id="invoice_form">

    <div class="row">
        <div class="large-12 columns">
            <h4>Invoice Header</h4>
            <label>Invoice Title
                <input type="text" name="invoice_title" placeholder="ex: Tax Invoice, Invoice" required/>
            </label>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <label>Invoice Date
                <input type="text" name="invoice_date" placeholder="" class="datepicker-invoicer" required/>
            </label>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <label>Invoice Number
                <input type="text" name="invoice_number" placeholder="" required/>
            </label>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <label>Currency Code
                <input type="text" name="currency_code" placeholder="ex: USD, LKR, $, SG$" required/>
            </label>
        </div>
    </div>
    <!--end header details-->

    <div class="row">
        <div class="large-6 columns">
            <div class="panel">
                <h5>Your Details</h5>

                <div class="row">
                    <div class="large-12 columns">
                        <label>Your Company Name
                            <input type="text" name="your_company_name" placeholder="" required/>
                        </label>
                    </div>
                </div>
                <!--div class="row">
                    <div class="large-12 columns">
                        <label>Company Logo URL
                            <input type="text" name="your_company_logo_url" placeholder="" required/>
                        </label>
                    </div>
                </div-->


                <div class="panel">
                    <h6>Contact Details</h6>

                    <div class="row">
                        <div class="large-12 columns">
                            <label>Address 1
                                <input type="text" name="your_address_1" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Address 2
                                <input type="text" name="your_address_2" placeholder=""/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>City
                                <input type="text" name="your_city" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>State
                                <input type="text" name="your_state" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Country
                                <input type="text" name="your_country" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Zip Code
                                <input type="text" name="your_zip_code" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Phone
                                <input type="text" name="your_phone" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Email
                                <input type="text" name="your_email" placeholder="" required type="email"/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Fax
                                <input type="text" name="your_fax" placeholder=""/>
                            </label>
                        </div>
                    </div>

                </div>

            </div>
        </div>

        <div class="large-6 columns">
            <div class="panel">
                <h5>Customer Details</h5>

                <div class="row">
                    <div class="large-12 columns">
                        <label>Customer Company Name
                            <input type="text" name="customer_company_name" placeholder="" required/>
                        </label>
                    </div>
                </div>
                <!--div class="row">
                    <div class="large-12 columns">
                        <label>Company Logo URL
                            <input type="text" name="customer_company_logo_url" placeholder="" required/>
                        </label>
                    </div>
                </div-->


                <div class="panel">
                    <h6>Contact Details</h6>

                    <div class="row">
                        <div class="large-12 columns">
                            <label>Address 1
                                <input type="text" name="customer_address_1" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Address 2
                                <input type="text" name="customer_address_2" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>City
                                <input type="text" name="customer_city" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>State
                                <input type="text" name="customer_state" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Country
                                <input type="text" name="customer_country" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Zip Code
                                <input type="text" name="customer_zip_code" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Phone
                                <input type="text" name="customer_phone" placeholder="" required/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Email
                                <input type="text" name="customer_email" placeholder="" required type="email"/>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label>Fax
                                <input type="text" name="customer_fax" placeholder=""/>
                            </label>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
    <!--end of contact Details-->

    <div class="row">
        <div class="large-12 columns">
            <h4>Invoice Details</h4>

            <a class="button round" onclick="javascript:addLineItem();">Add Line Item</a>

            <table id="invoice-details-table">
                <thead>
                <tr>
                    <th>Line No</th>
                    <th>Item</th>
                    <th>Description</th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><input type="text" placeholder="" class="item_no" name="item_no[]" required/></td>
                    <td><input type="text" placeholder="" class="item" name="item[]" required/></td>
                    <td><input type="text" placeholder="" class="description" name="description[]" required/></td>
                    <td><input type="text" placeholder="" class="unit_price" name="unit_price[]" onchange="calculateTotal()" required/></td>
                    <td><input type="text" placeholder="" class="quantity" name="quantity[]" onchange="calculateTotal()" required/></td>
                    <td><input type="text" placeholder="" class="total" name="total[]" value="0" required readonly/></td>
                    <td><input type="button" class="button small alert round" value="X" onclick="removeLineItem(this)"/></td>
                </tr>


                </tbody>
            </table>

            <table>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>Sub Total</th>
                    <td><input type="text" id="sub_total" name="sub_total" value="0" readonly required/></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>Taxes %</th>
                    <td><input type="text" id="taxes" name="taxes" value="0" placeholder="%"
                               onchange="calculateSubTotals()" required/></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>Discounts %</th>
                    <td><input type="text" id="discounts" name="discounts" value="0" placeholder="%"
                               onchange="calculateSubTotals()" required/></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>Total Due</th>
                    <td><input type="text" id="total_due" name="total_due" value="0" readonly required/></td>
                </tr>

            </table>
            <p>Final values on the invoice are formatted to 2 decimal places.</p>
        </div>
    </div>
    <!--end header details-->

    <div class="row">
        <div class="large-12 columns">
            <h4>Invoice Terms & Notes</h4>

            <div class="row">
                <div class="large-12 columns">
                    <label>Terms
                        <textarea name="terms" placeholder="" required></textarea>
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <label>Notes
                        <textarea name="notes" placeholder="" required></textarea>
                    </label>
                </div>
            </div>
        </div>
    </div>
    <!--end terms and notes-->

    <div class="row">
        <div class="large-12 columns">
            <h4>Actions</h4>

            <div class="row text-center">
                <div class="large-12 columns">
                    <div class="g-recaptcha" data-sitekey="6LcsmAQTAAAAAIKkuHijL8SQbMSL-vxlzJIyZAau"></div>
                </div>
            </div>

            <div class="row text-center">
                <div class="large-12 columns">
                    <input type="submit" class="button success round" value="Generate PDF"/>
                </div>
            </div>
        </div>
    </div>

</form>

<div class="row footer">
    <div class="large-12 columns text-center">
        <p class="copyright">&copy; <?php echo date('Y'); ?> Suren Dias. <a href="http://surendias.com" target="_blank">web</a> . <a href="http://codias.wordpress.com" target="_blank">blog</a></p>
    </div>
</div>


<script src="js/vendor/jquery.js"></script>
<script src="js/foundation.min.js"></script>
<script src="js/foundation-datepicker.js"></script>
<script src="js/jquery.validate.js"></script>

<script>
    $(document).foundation();

    $('.datepicker-invoicer').fdatepicker({});
</script>

<script>


    $().ready(function() {
        // validate the comment form when it is submitted
        $("#invoice_form").validate();
    });
</script>

<script>
    function addLineItem() {

        var table = document.getElementById('invoice-details-table');

        var row = table.insertRow();


        var cell1 = row.insertCell(0);
        var cell2 = row.insertCell(1);
        var cell3 = row.insertCell(2);
        var cell4 = row.insertCell(3);
        var cell5 = row.insertCell(4);
        var cell6 = row.insertCell(5);
        var cell7 = row.insertCell(6);

        cell1.innerHTML = '<input type="text" placeholder="" class="item_no" name="item_no[]" />';
        cell2.innerHTML = '<input type="text" placeholder="" class="item" name="item[]" />';
        cell3.innerHTML = '<input type="text" placeholder="" class="description" name="description[]" />';
        cell4.innerHTML = '<input type="text" placeholder="" class="unit_price" name="unit_price[]" onchange="calculateTotal()" />';
        cell5.innerHTML = '<input type="text" placeholder="" class="quantity" name="quantity[]" onchange="calculateTotal()" />';
        cell6.innerHTML = '<input type="text" placeholder="" class="total" name="total[]" value="0" readonly />';
        cell7.innerHTML = '<input type="button" class="button small alert round" value="X" onclick="removeLineItem(this)"/>';


    }

    function removeLineItem(row) {
        var i = row.parentNode.parentNode.rowIndex;
        document.getElementById("invoice-details-table").deleteRow(i);
        calculateSubTotals();
    }

    function calculateTotal() {
        var unit_prices = document.getElementsByClassName("unit_price");
        var quantities = document.getElementsByClassName("quantity");
        var totals = document.getElementsByClassName("total");
        for (var i = 0; i < totals.length; i++) {
            //alert(totals[i].value);

            if (!isNaN(unit_prices[i].value) && unit_prices[i].value != '' && unit_prices[i].value != undefined && !isNaN(quantities[i].value) && quantities[i].value != '' && quantities[i].value != undefined)
                totals[i].value = parseFloat(unit_prices[i].value) * parseFloat(quantities[i].value);
        }

        calculateSubTotals();
    }

    function calculateSubTotals() {

        var sub_total = 0;
        var totals = document.getElementsByClassName("total");
        //alert(totals.length);
        for (var i = 0; i < totals.length; i++) {
            //alert(totals[i].value);
            if (!isNaN(totals[i].value) && totals[i].value != '' && totals[i].value != undefined)
                sub_total += parseFloat(totals[i].value);
        }

        var taxes = sub_total * parseFloat(document.getElementById('taxes').value) / 100;
        var discounts = sub_total * parseFloat(document.getElementById('discounts').value) / 100;

        if (isNaN(taxes) || taxes == '' || taxes == undefined)
            taxes = 0;

        if (isNaN(discounts) || discounts == '' || discounts == undefined)
            discounts = 0;


        document.getElementById('sub_total').value = sub_total;
        document.getElementById('total_due').value = sub_total + taxes - discounts;

    }
</script>

</body>
</html>
